### ISSUE TITLE
Need rich readme for gulp-letters

### ISSUE THREAD

**Issue by kazimirchan** [andreymaznyak/gulp-letters#3]
В readme есть только перечень доступных галп тасков, но нет примера по использованию. Например, строчка:
> `gulp new -n test`  - создает письмо под названием test в папке dev

Сильно упростила бы жизнь. Самым лучшим вариантом является описание полного цикла создания письма через данную библиотеку: от установки библиотеки и создания нового письма, до его удаления.

То же самое касается использования переменных. Непонятно, где нужно прописать переменную и, чтобы она была доступна для pug.

**Comment by andreymaznyak** [comment]
@mkitaev  Миша, добавь доку.

**Comment by mkitaev** [comment]
@J-Veber readme upd. Need feedback.

**Comment by kazimirchan** [comment]
@mkitaev добавь нюансы работы с gulp файлом

**Comment by mkitaev** [comment]
@J-Veber please check russian lang readme for more information
